target("core")
    set_group("Spar")
    set_default(false)
    set_kind("static")
    add_deps("Math", {public = true})
    add_files("Core/**.cpp")
    add_headerfiles("Core/**.h")
    add_packages("stb", "cgltf", "fastgltf", {public = true})
    add_includedirs("core", {public = true})
target_end()

target("renderer")
    set_group("Spar")
    set_default(false)
    set_kind("static")
    add_deps("core", {public = true})
    add_files("Renderer/**.cpp")
    add_headerfiles("Renderer/**.h")
    add_packages("libsdl", {public = true})
    add_includedirs("renderer", {public = true})
target_end()

